Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(figsize=(5,5)) 
ax.set_ylim([-1.5, 0.5])
ax.set_xlim([1, -1])
pendulum1, = ax.plot([], [], color="red", lw=2)
pendulum2, = ax.plot([], [], color="blue", lw=2)

def init():
    pendulum1.set_data([], [])
    pendulum2.set_data([], [])
    return pendulum1, pendulum2  # Return the artists

def update(n):
    # n = frame counter
    # calculate the positions of the pendulums 
    x1 = + L * sin(x[n, 0])
    y1 = - L * cos(x[n, 0])
    x2 = x1 + L * sin(x[n, 1])
    y2 = y1 - L * cos(x[n, 1])
    # update the line data
    pendulum1.set_data([0 ,x1], [0 ,y1])
    pendulum2.set_data([x1,x2], [y1,y2])
    return pendulum1, pendulum2  # Return the artists
    
anim = animation.FuncAnimation(fig, update, init_func=init, frames=len(t), blit=True)
# anim.save can be called in a few different ways, some which might or might not work
# on different platforms and with different versions of matplotlib and video encoders #anim.save(â€™animation.mp4â€™, fps=20, extra_args=[â€™-vcodecâ€™, â€™libx264â€™], writer=animation.FFMpegWriter()) #anim.save(â€™animation.mp4â€™, fps=20, extra_args=[â€™-vcodecâ€™, â€™libx264â€™])
#anim.save("animation.mp4", fps=20, writer="ffmpeg", codec="libx264")
#anim.save("animation.mp4", fps=20, writer="avconv", codec="libx264")
anim.save("animation.mp4", fps=20)
plt.close(fig)
------------------

----- stderr -----
MovieWriter ffmpeg unavailable; using Pillow instead.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/PIL/Image.py:2580[0m, in [0;36mImage.save[0;34m(self, fp, format, **params)[0m
[1;32m   2579[0m [38;5;28;01mtry[39;00m:
[0;32m-> 2580[0m     [38;5;28mformat[39m [38;5;241m=[39m [43mEXTENSION[49m[43m[[49m[43mext[49m[43m][49m
[1;32m   2581[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m e:

[0;31mKeyError[0m: '.mp4'

The above exception was the direct cause of the following exception:

[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[25], line 29[0m
[1;32m     24[0m anim [38;5;241m=[39m animation[38;5;241m.[39mFuncAnimation(fig, update, init_func[38;5;241m=[39minit, frames[38;5;241m=[39m[38;5;28mlen[39m(t), blit[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     25[0m [38;5;66;03m# anim.save can be called in a few different ways, some which might or might not work[39;00m
[1;32m     26[0m [38;5;66;03m# on different platforms and with different versions of matplotlib and video encoders #anim.save(â€™animation.mp4â€™, fps=20, extra_args=[â€™-vcodecâ€™, â€™libx264â€™], writer=animation.FFMpegWriter()) #anim.save(â€™animation.mp4â€™, fps=20, extra_args=[â€™-vcodecâ€™, â€™libx264â€™])[39;00m
[1;32m     27[0m [38;5;66;03m#anim.save("animation.mp4", fps=20, writer="ffmpeg", codec="libx264")[39;00m
[1;32m     28[0m [38;5;66;03m#anim.save("animation.mp4", fps=20, writer="avconv", codec="libx264")[39;00m
[0;32m---> 29[0m [43manim[49m[38;5;241;43m.[39;49m[43msave[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43manimation.mp4[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mfps[49m[38;5;241;43m=[39;49m[38;5;241;43m20[39;49m[43m)[49m
[1;32m     30[0m plt[38;5;241m.[39mclose(fig)

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/matplotlib/animation.py:1069[0m, in [0;36mAnimation.save[0;34m(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs, progress_callback)[0m
[1;32m   1065[0m savefig_kwargs[[38;5;124m'[39m[38;5;124mtransparent[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28;01mFalse[39;00m   [38;5;66;03m# just to be safe![39;00m
[1;32m   1066[0m [38;5;66;03m# canvas._is_saving = True makes the draw_event animation-starting[39;00m
[1;32m   1067[0m [38;5;66;03m# callback a no-op; canvas.manager = None prevents resizing the GUI[39;00m
[1;32m   1068[0m [38;5;66;03m# widget (both are likewise done in savefig()).[39;00m
[0;32m-> 1069[0m [43m[49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mwriter[49m[38;5;241;43m.[39;49m[43msaving[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_fig[49m[43m,[49m[43m [49m[43mfilename[49m[43m,[49m[43m [49m[43mdpi[49m[43m)[49m[43m,[49m[43m [49m[43m\[49m
[1;32m   1070[0m [43m     [49m[43mcbook[49m[38;5;241;43m.[39;49m[43m_setattr_cm[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_fig[49m[38;5;241;43m.[39;49m[43mcanvas[49m[43m,[49m[43m [49m[43m_is_saving[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mmanager[49m[38;5;241;43m=[39;49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m:[49m
[1;32m   1071[0m [43m    [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43manim[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[43mall_anim[49m[43m:[49m
[1;32m   1072[0m [43m        [49m[43manim[49m[38;5;241;43m.[39;49m[43m_init_draw[49m[43m([49m[43m)[49m[43m  [49m[38;5;66;43;03m# Clear the initial frame[39;49;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/contextlib.py:144[0m, in [0;36m_GeneratorContextManager.__exit__[0;34m(self, typ, value, traceback)[0m
[1;32m    142[0m [38;5;28;01mif[39;00m typ [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    143[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 144[0m         [38;5;28mnext[39m([38;5;28mself[39m[38;5;241m.[39mgen)
[1;32m    145[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[1;32m    146[0m         [38;5;28;01mreturn[39;00m [38;5;28;01mFalse[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/matplotlib/animation.py:225[0m, in [0;36mAbstractMovieWriter.saving[0;34m(self, fig, outfile, dpi, *args, **kwargs)[0m
[1;32m    223[0m     [38;5;28;01myield[39;00m [38;5;28mself[39m
[1;32m    224[0m [38;5;28;01mfinally[39;00m:
[0;32m--> 225[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfinish[49m[43m([49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/matplotlib/animation.py:495[0m, in [0;36mPillowWriter.finish[0;34m(self)[0m
[1;32m    494[0m [38;5;28;01mdef[39;00m [38;5;21mfinish[39m([38;5;28mself[39m):
[0;32m--> 495[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_frames[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[38;5;241;43m.[39;49m[43msave[49m[43m([49m
[1;32m    496[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43moutfile[49m[43m,[49m[43m [49m[43msave_all[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mappend_images[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_frames[49m[43m[[49m[38;5;241;43m1[39;49m[43m:[49m[43m][49m[43m,[49m
[1;32m    497[0m [43m        [49m[43mduration[49m[38;5;241;43m=[39;49m[38;5;28;43mint[39;49m[43m([49m[38;5;241;43m1000[39;49m[43m [49m[38;5;241;43m/[39;49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfps[49m[43m)[49m[43m,[49m[43m [49m[43mloop[49m[38;5;241;43m=[39;49m[38;5;241;43m0[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/PIL/Image.py:2583[0m, in [0;36mImage.save[0;34m(self, fp, format, **params)[0m
[1;32m   2581[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m e:
[1;32m   2582[0m         msg [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124munknown file extension: [39m[38;5;132;01m{[39;00mext[38;5;132;01m}[39;00m[38;5;124m"[39m
[0;32m-> 2583[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(msg) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m   2585[0m [38;5;28;01mif[39;00m [38;5;28mformat[39m[38;5;241m.[39mupper() [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m SAVE:
[1;32m   2586[0m     init()

[0;31mValueError[0m: unknown file extension: .mp4

