Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np

import matplotlib.pyplot as plt
def random_walk(seed, nsteps, ax):
    rng = np.random.default_rng(seed=seed)
    x = np.zeros(nsteps)
    y = np.zeros(nsteps)
    # YOUR CODE HERE
    raise NotImplementedError()
    ax.plot(x, y)
    
NSTEPS = 10000
fig, ax = plt.subplots()
random_walk(10, NSTEPS, ax)
random_walk(2, NSTEPS, ax)
random_walk(7, NSTEPS, ax)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNotImplementedError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 14[0m
[1;32m     12[0m NSTEPS [38;5;241m=[39m [38;5;241m10000[39m
[1;32m     13[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[0;32m---> 14[0m [43mrandom_walk[49m[43m([49m[38;5;241;43m10[39;49m[43m,[49m[43m [49m[43mNSTEPS[49m[43m,[49m[43m [49m[43max[49m[43m)[49m
[1;32m     15[0m random_walk([38;5;241m2[39m, NSTEPS, ax)
[1;32m     16[0m random_walk([38;5;241m7[39m, NSTEPS, ax)

Cell [0;32mIn[1], line 9[0m, in [0;36mrandom_walk[0;34m(seed, nsteps, ax)[0m
[1;32m      7[0m y [38;5;241m=[39m np[38;5;241m.[39mzeros(nsteps)
[1;32m      8[0m [38;5;66;03m# YOUR CODE HERE[39;00m
[0;32m----> 9[0m [38;5;28;01mraise[39;00m [38;5;167;01mNotImplementedError[39;00m()
[1;32m     10[0m ax[38;5;241m.[39mplot(x, y)

[0;31mNotImplementedError[0m: 

