Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Animation
import matplotlib.animation as animation
fig, ax = plt.subplots()
ax.set_xlim([0, T[-1]])
ax.set_ylim([Ry.min(), Ry.max()])
line, = ax.plot([], [],'o')

def init():
    line.set_data([], [])
    return line,

def animate(i):
    line.set_data(T[i], Ry[i])
    return line,

anim = animation.FuncAnimation(fig, animate, init_func=init,
                               frames=NSTEPS, interval=20, blit=False)
anim.save('ParticleGravity.mp4', fps=30)
------------------

----- stderr -----
MovieWriter ffmpeg unavailable; using Pillow instead.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/matplotlib/animation.py:224[0m, in [0;36mAbstractMovieWriter.saving[0;34m(self, fig, outfile, dpi, *args, **kwargs)[0m
[1;32m    223[0m [38;5;28;01mtry[39;00m:
[0;32m--> 224[0m     [38;5;28;01myield[39;00m [38;5;28mself[39m
[1;32m    225[0m [38;5;28;01mfinally[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/matplotlib/animation.py:1122[0m, in [0;36mAnimation.save[0;34m(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs, progress_callback)[0m
[1;32m   1120[0m [38;5;28;01mfor[39;00m anim, d [38;5;129;01min[39;00m [38;5;28mzip[39m(all_anim, data):
[1;32m   1121[0m     [38;5;66;03m# TODO: See if turning off blit is really necessary[39;00m
[0;32m-> 1122[0m     [43manim[49m[38;5;241;43m.[39;49m[43m_draw_next_frame[49m[43m([49m[43md[49m[43m,[49m[43m [49m[43mblit[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m
[1;32m   1123[0m     [38;5;28;01mif[39;00m progress_callback [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/matplotlib/animation.py:1157[0m, in [0;36mAnimation._draw_next_frame[0;34m(self, framedata, blit)[0m
[1;32m   1156[0m [38;5;28mself[39m[38;5;241m.[39m_pre_draw(framedata, blit)
[0;32m-> 1157[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_draw_frame[49m[43m([49m[43mframedata[49m[43m)[49m
[1;32m   1158[0m [38;5;28mself[39m[38;5;241m.[39m_post_draw(framedata, blit)

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/matplotlib/animation.py:1789[0m, in [0;36mFuncAnimation._draw_frame[0;34m(self, framedata)[0m
[1;32m   1787[0m [38;5;66;03m# Call the func with framedata and args. If blitting is desired,[39;00m
[1;32m   1788[0m [38;5;66;03m# func needs to return a sequence of any artists that were modified.[39;00m
[0;32m-> 1789[0m [38;5;28mself[39m[38;5;241m.[39m_drawn_artists [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_func[49m[43m([49m[43mframedata[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_args[49m[43m)[49m
[1;32m   1791[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_blit:

Cell [0;32mIn[7], line 13[0m, in [0;36manimate[0;34m(i)[0m
[1;32m     12[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21manimate[39m(i):
[0;32m---> 13[0m     [43mline[49m[38;5;241;43m.[39;49m[43mset_data[49m[43m([49m[43mT[49m[43m[[49m[43mi[49m[43m][49m[43m,[49m[43m [49m[43mRy[49m[43m[[49m[43mi[49m[43m][49m[43m)[49m
[1;32m     14[0m     [38;5;28;01mreturn[39;00m line,

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/matplotlib/lines.py:666[0m, in [0;36mLine2D.set_data[0;34m(self, *args)[0m
[1;32m    664[0m     x, y [38;5;241m=[39m args
[0;32m--> 666[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mset_xdata[49m[43m([49m[43mx[49m[43m)[49m
[1;32m    667[0m [38;5;28mself[39m[38;5;241m.[39mset_ydata(y)

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/matplotlib/lines.py:1290[0m, in [0;36mLine2D.set_xdata[0;34m(self, x)[0m
[1;32m   1289[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m np[38;5;241m.[39miterable(x):
[0;32m-> 1290[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m'[39m[38;5;124mx must be a sequence[39m[38;5;124m'[39m)
[1;32m   1291[0m [38;5;28mself[39m[38;5;241m.[39m_xorig [38;5;241m=[39m copy[38;5;241m.[39mcopy(x)

[0;31mRuntimeError[0m: x must be a sequence

During handling of the above exception, another exception occurred:

[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[7], line 18[0m
[1;32m     14[0m     [38;5;28;01mreturn[39;00m line,
[1;32m     16[0m anim [38;5;241m=[39m animation[38;5;241m.[39mFuncAnimation(fig, animate, init_func[38;5;241m=[39minit,
[1;32m     17[0m                                frames[38;5;241m=[39mNSTEPS, interval[38;5;241m=[39m[38;5;241m20[39m, blit[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[0;32m---> 18[0m [43manim[49m[38;5;241;43m.[39;49m[43msave[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mParticleGravity.mp4[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mfps[49m[38;5;241;43m=[39;49m[38;5;241;43m30[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/matplotlib/animation.py:1098[0m, in [0;36mAnimation.save[0;34m(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs, progress_callback)[0m
[1;32m   1093[0m     [38;5;28;01mreturn[39;00m a [38;5;241m*[39m np[38;5;241m.[39marray([r, g, b]) [38;5;241m+[39m [38;5;241m1[39m [38;5;241m-[39m a
[1;32m   1095[0m [38;5;66;03m# canvas._is_saving = True makes the draw_event animation-starting[39;00m
[1;32m   1096[0m [38;5;66;03m# callback a no-op; canvas.manager = None prevents resizing the GUI[39;00m
[1;32m   1097[0m [38;5;66;03m# widget (both are likewise done in savefig()).[39;00m
[0;32m-> 1098[0m [43m[49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43m([49m[43mwriter[49m[38;5;241;43m.[39;49m[43msaving[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_fig[49m[43m,[49m[43m [49m[43mfilename[49m[43m,[49m[43m [49m[43mdpi[49m[43m)[49m[43m,[49m
[1;32m   1099[0m [43m      [49m[43mcbook[49m[38;5;241;43m.[39;49m[43m_setattr_cm[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_fig[49m[38;5;241;43m.[39;49m[43mcanvas[49m[43m,[49m[43m [49m[43m_is_saving[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mmanager[49m[38;5;241;43m=[39;49m[38;5;28;43;01mNone[39;49;00m[43m)[49m[43m)[49m[43m:[49m
[1;32m   1100[0m [43m    [49m[38;5;28;43;01mif[39;49;00m[43m [49m[38;5;129;43;01mnot[39;49;00m[43m [49m[43mwriter[49m[38;5;241;43m.[39;49m[43m_supports_transparency[49m[43m([49m[43m)[49m[43m:[49m
[1;32m   1101[0m [43m        [49m[43mfacecolor[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43msavefig_kwargs[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mfacecolor[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m   1102[0m [43m                                       [49m[43mmpl[49m[38;5;241;43m.[39;49m[43mrcParams[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43msavefig.facecolor[39;49m[38;5;124;43m'[39;49m[43m][49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/contextlib.py:158[0m, in [0;36m_GeneratorContextManager.__exit__[0;34m(self, typ, value, traceback)[0m
[1;32m    156[0m     value [38;5;241m=[39m typ()
[1;32m    157[0m [38;5;28;01mtry[39;00m:
[0;32m--> 158[0m     [38;5;28mself[39m[38;5;241m.[39mgen[38;5;241m.[39mthrow(typ, value, traceback)
[1;32m    159[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m [38;5;28;01mas[39;00m exc:
[1;32m    160[0m     [38;5;66;03m# Suppress StopIteration *unless* it's the same exception that[39;00m
[1;32m    161[0m     [38;5;66;03m# was passed to throw().  This prevents a StopIteration[39;00m
[1;32m    162[0m     [38;5;66;03m# raised inside the "with" statement from being suppressed.[39;00m
[1;32m    163[0m     [38;5;28;01mreturn[39;00m exc [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m value

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/matplotlib/animation.py:226[0m, in [0;36mAbstractMovieWriter.saving[0;34m(self, fig, outfile, dpi, *args, **kwargs)[0m
[1;32m    224[0m     [38;5;28;01myield[39;00m [38;5;28mself[39m
[1;32m    225[0m [38;5;28;01mfinally[39;00m:
[0;32m--> 226[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfinish[49m[43m([49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/matplotlib/animation.py:506[0m, in [0;36mPillowWriter.finish[0;34m(self)[0m
[1;32m    505[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mfinish[39m([38;5;28mself[39m):
[0;32m--> 506[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_frames[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[38;5;241m.[39msave(
[1;32m    507[0m         [38;5;28mself[39m[38;5;241m.[39moutfile, save_all[38;5;241m=[39m[38;5;28;01mTrue[39;00m, append_images[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_frames[[38;5;241m1[39m:],
[1;32m    508[0m         duration[38;5;241m=[39m[38;5;28mint[39m([38;5;241m1000[39m [38;5;241m/[39m [38;5;28mself[39m[38;5;241m.[39mfps), loop[38;5;241m=[39m[38;5;241m0[39m)

[0;31mIndexError[0m: list index out of range

