Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import vpython as vp
#import visual as vp
vp.sphere()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mvpython[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mvp[39;00m
[1;32m      2[0m [38;5;66;03m#import visual as vp[39;00m
[0;32m----> 3[0m [43mvp[49m[38;5;241;43m.[39;49m[43msphere[49m[43m([49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/vpython/vpython.py:1189[0m, in [0;36msphere.__init__[0;34m(self, **args)[0m
[1;32m   1187[0m args[[38;5;124m'[39m[38;5;124m_default_size[39m[38;5;124m'[39m] [38;5;241m=[39m vector([38;5;241m2[39m,[38;5;241m2[39m,[38;5;241m2[39m)
[1;32m   1188[0m args[[38;5;124m'[39m[38;5;124m_objName[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;124m"[39m[38;5;124msphere[39m[38;5;124m"[39m
[0;32m-> 1189[0m [38;5;28;43msuper[39;49m[43m([49m[43msphere[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m[38;5;241;43m.[39;49m[43msetup[49m[43m([49m[43margs[49m[43m)[49m
[1;32m   1190[0m [38;5;28mself[39m[38;5;241m.[39m_sizing [38;5;241m=[39m [38;5;28;01mFalse[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/vpython/vpython.py:612[0m, in [0;36mstandardAttributes.setup[0;34m(self, args)[0m
[1;32m    611[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21msetup[39m([38;5;28mself[39m, args):
[0;32m--> 612[0m     [38;5;28;43msuper[39;49m[43m([49m[43mstandardAttributes[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[43m)[49m
[1;32m    613[0m     [38;5;28mself[39m[38;5;241m.[39m_constructing [38;5;241m=[39m [38;5;28;01mTrue[39;00m  [38;5;66;03m## calls to setters are from constructor[39;00m
[1;32m    615[0m     objName [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_objName [38;5;241m=[39m args[[38;5;124m'[39m[38;5;124m_objName[39m[38;5;124m'[39m]  [38;5;66;03m## identifies object type[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/vpython/vpython.py:265[0m, in [0;36mbaseObj.__init__[0;34m(self, **kwargs)[0m
[1;32m    262[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m (baseObj[38;5;241m.[39m_view_constructed [38;5;129;01mor[39;00m
[1;32m    263[0m         baseObj[38;5;241m.[39m_canvas_constructing):
[1;32m    264[0m     [38;5;28;01mif[39;00m _isnotebook:
[0;32m--> 265[0m         [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mwith_notebook[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m _
[1;32m    266[0m     [38;5;28;01melse[39;00m:
[1;32m    267[0m         [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mno_notebook[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m _

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/vpython/with_notebook.py:71[0m
[1;32m     66[0m         [38;5;28;01mexcept[39;00m [38;5;167;01mPermissionError[39;00m:
[1;32m     67[0m             [38;5;66;03m#logging.info("PermissionError: Unable to install /vpython_data directory and files for VPython on JupyterLab")[39;00m
[1;32m     68[0m             [38;5;28;01mpass[39;00m
[0;32m---> 71[0m [38;5;28;01mif[39;00m ([38;5;124m'[39m[38;5;124mnbextensions[39m[38;5;124m'[39m [38;5;129;01min[39;00m [43mos[49m[38;5;241;43m.[39;49m[43mlistdir[49m[43m([49m[43mjd[49m[43m)[49m) [38;5;129;01mand[39;00m (notebook[38;5;241m.[39m__version__ [38;5;241m<[39m[38;5;241m=[39m [38;5;124m'[39m[38;5;124m6.5.5[39m[38;5;124m'[39m):
[1;32m     72[0m     ldir [38;5;241m=[39m os[38;5;241m.[39mlistdir(nbdir)
[1;32m     73[0m     [38;5;28;01mif[39;00m ([38;5;124m'[39m[38;5;124mvpython_data[39m[38;5;124m'[39m [38;5;129;01min[39;00m ldir [38;5;129;01mand[39;00m [38;5;28mlen[39m(os[38;5;241m.[39mlistdir(nbdata)) [38;5;241m==[39m datacnt [38;5;129;01mand[39;00m
[1;32m     74[0m        [38;5;124m'[39m[38;5;124mvpython_libraries[39m[38;5;124m'[39m [38;5;129;01min[39;00m ldir [38;5;129;01mand[39;00m [38;5;28mlen[39m(os[38;5;241m.[39mlistdir(nblib)) [38;5;241m==[39m libcnt [38;5;129;01mand[39;00m
[1;32m     75[0m         [38;5;124m'[39m[38;5;124mvpython_version.txt[39m[38;5;124m'[39m [38;5;129;01min[39;00m ldir):

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/runner/.local/share/jupyter'

